return {
  "LunarVim/bigfile.nvim",
  config = function()
    require("bigfile").setup({
      filesize = 2, -- size of the file in MiB, the plugin round file sizes to the closest MiB
      pattern = { "*" }, -- autocmd pattern or function see <### Overriding the detection of big files>
      features = { -- features to disable
        "indent_blankline",
        "illuminate",
        "lsp",
        "treesitter",
        "syntax",
        "matchparen",
        "vimopts",
        "filetype",
        "neo-tree.nvim",
        "LuaSnip",
        "SchemaStore.nvim ",
        "SnippetGenie ",
        "awesome-vim-colorschemes ",
        "ccc.nvim ",
        "cmp-buffer ",
        "cmp-emoji ",
        "cmp-nvim-lsp ",
        "cmp-path ",
        "cmp-tmux ",
        "cmp_luasnip ",
        "diffview.nvim ",
        "dracula.nvim ",
        "guess-indent.nvim ",
        "marks.nvim ",
        "mini.ai ",
        "mini.comment ",
        "mini.trailspace ",
        "neo-hybrid.vim ",
        "neoconf-venom.nvim ",
        "null-ls.nvim ",
        "nvim-autopairs ",
        "nvim-blackline ",
        "nvim-navic ",
        "nvim-notify ",
        "nvim-surround ",
        "nvim-treesitter-endwise ",
        "nvim-ts-autotag ",
        "nvim-ts-context-commentstring ",
        "nvim-web-devicons ",
        "nvim-window-picker ",
        "persisted.nvim ",
        "spelunker.vim ",
        "suda.vim ",
        "theme-loader.nvim ",
        "todo-comments.nvim ",
        "vim-colors-xcode ",
        "vim-illuminate ",
        "vim-matchup ",
        "vim-tmux-navigator ",
        "vim-visual-multi ",
        "which-key.nvim ",
      },
    })
  end,
}
